DROP TABLE IF EXISTS precondition;
CREATE TABLE precondition (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS systemname;
CREATE TABLE systemname (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE  IF EXISTS modalverb;
CREATE TABLE modalverb (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS activities;
CREATE TABLE activities (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS objects;
CREATE TABLE objects (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS details;
CREATE TABLE details (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);