DROP TABLE IF EXISTS PRECONDITION;
CREATE TABLE PRECONDITION (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS SYSTEMNAME;
CREATE TABLE SYSTEMNAME (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE  IF EXISTS MODALVERB;
CREATE TABLE MODALVERB (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS ACTIVITIES;
CREATE TABLE ACTIVITIES (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS OBJECT;
CREATE TABLE OBJECT (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS DETAILS;
CREATE TABLE DETAILS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	KEY_NAME VARCHAR(50) NOT NULL,
	REGEX VARCHAR(255) NOT NULL,
	REQUIRED INTEGER NOT NULL,
	PRIMARY KEY(ID)
);